# All D11 Calculation Pathways

Evaluate all 32 slab-level `D11` pathways on ECTP slabs, export the paper-ready distribution
figure, and assemble the representative-pathways table used in the manuscript.

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

from notebook_utils import create_ectp_slabs, hess_rcparams, load_pits
from paper_figure_utils import (
    build_d11_distribution_figure,
    notebook_latex,
    prepare_d11_top_pathways_table,
    save_paper_figure,
)
from snowpyt_mechparams.algorithm import find_parameterizations
from snowpyt_mechparams.execution import ExecutionEngine
from snowpyt_mechparams.execution.config import ExecutionConfig
from snowpyt_mechparams.graph import graph

hess_rcparams()

## Load Data and Execute All D11 Paths

In [2]:
pits = load_pits()
ectp_slabs = create_ectp_slabs(pits)
total_slabs = len(ectp_slabs)
pathways = find_parameterizations(graph, graph.get_node('D11'))

engine = ExecutionEngine(graph)
config = ExecutionConfig(include_method_uncertainty=False)

pathway_slab_success = {}
pathway_rel_unc = {}
pathway_nominal = {}

for slab in ectp_slabs:
    results = engine.execute_all(slab, 'D11', config=config)
    for pathway_result in results.pathways.values():
        density_method = pathway_result.methods_used.get('density', 'unknown')
        emod_method = pathway_result.methods_used.get('elastic_modulus', 'unknown')
        nu_method = pathway_result.methods_used.get('poissons_ratio', 'unknown')
        pathway_key = f'{density_method} -> {emod_method} -> {nu_method}'

        pathway_slab_success.setdefault(pathway_key, 0)
        pathway_rel_unc.setdefault(pathway_key, [])
        pathway_nominal.setdefault(pathway_key, [])

        d11_nominal = None
        d11_std = None
        for trace in pathway_result.computation_trace:
            if trace.parameter == 'D11' and trace.success and trace.output is not None:
                output = trace.output
                if hasattr(output, 'nominal_value'):
                    d11_nominal = float(output.nominal_value)
                    d11_std = float(output.std_dev)
                else:
                    d11_nominal = float(output)
                    d11_std = 0.0
                break

        if d11_nominal is not None:
            pathway_slab_success[pathway_key] += 1
            pathway_nominal[pathway_key].append(d11_nominal)
            if d11_nominal != 0 and d11_std is not None:
                pathway_rel_unc[pathway_key].append(d11_std / abs(d11_nominal))

ordered_paths = sorted(pathway_slab_success.items(), key=lambda item: item[1], reverse=True)

summary_rows = []
for pathway_key, n_success in ordered_paths:
    nominal_values = np.asarray(pathway_nominal[pathway_key], dtype=float)
    rel_unc = np.asarray(pathway_rel_unc[pathway_key], dtype=float)
    summary_rows.append(
        {
            'Pathway': pathway_key,
            'Slabs': int(n_success),
            'Coverage (%)': f'{100.0 * n_success / total_slabs:.1f}',
            'Mean D11 (N m)': f'{np.mean(nominal_values):.3e}',
            'Mean relative uncertainty (%)': f'{100.0 * np.mean(rel_unc):.1f}',
        }
    )

d11_summary = pd.DataFrame(summary_rows)
print(f'Loaded {len(pits):,} pits, {total_slabs:,} ECTP slabs, and {len(pathways)} D11 pathways')
d11_summary.head(12)

Loaded 50,278 pits, 14,776 ECTP slabs, and 32 D11 pathways

,Pathway,Slabs,Coverage (%),Mean D11 (N m),Mean relative uncertainty (%)
0,kim_jamieson_table2 -> wautier -> kochle,743,5.0,2.219e+09,37.4
1,kim_jamieson_table2 -> schottner -> kochle,743,5.0,8.829e+07,73.3
2,geldsetzer -> wautier -> kochle,740,5.0,2.282e+09,38.2
3,geldsetzer -> schottner -> kochle,740,5.0,9.024e+07,75.0
4,geldsetzer -> kochle -> kochle,733,5.0,4.441e+08,81.9
5,kim_jamieson_table2 -> kochle -> kochle,634,4.3,4.460e+08,85.3
6,kim_jamieson_table2 -> bergfeld -> kochle,498,3.4,6.828e+07,75.4
7,geldsetzer -> bergfeld -> kochle,475,3.2,7.164e+07,76.8
8,geldsetzer -> wautier -> srivastava,449,3.0,1.681e+09,45.4
9,geldsetzer -> schottner -> srivastava,449,3.0,7.196e+07,87.2
10,kim_jamieson_table2 -> wautier -> srivastava,446,3.0,1.637e+09,39.5
11,kim_jamieson_table2 -> schottner -> srivastava,446,3.0,7.044e+07,74.5

## Export Figure and Representative Table

In [3]:
d11_paths = save_paper_figure(
    build_d11_distribution_figure(ordered_paths, pathway_nominal, total_slabs, top_n=12),
    'd11_top_pathways',
    close=True,
)
top_pathways_table = prepare_d11_top_pathways_table(
    d11_summary,
    ordered_paths,
    pathway_nominal,
    top_n=12,
)
print('D11 figure exports:', d11_paths)
top_pathways_table

D11 figure exports: {'pdf': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/d11_top_pathways.pdf'), 'png': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/d11_top_pathways.png')}

,Pathway,Successful slabs,Coverage (%),Mean D11 (N m),Mean relative uncertainty (%)
0,Kim and Jamieson Table 2 -> Wautier et al. (20...,743,5.0,$2.219 \times 10^{9}$,37.4
1,Kim and Jamieson Table 2 -> Schottner et al. (...,743,5.0,$8.829 \times 10^{7}$,73.3
2,Geldsetzer and Jamieson (2000) -> Wautier et a...,740,5.0,$2.282 \times 10^{9}$,38.2
3,Geldsetzer and Jamieson (2000) -> Schottner et...,740,5.0,$9.024 \times 10^{7}$,75.0
4,Geldsetzer and Jamieson (2000) -> Kochle and S...,733,5.0,$4.441 \times 10^{8}$,81.9
5,Kim and Jamieson Table 2 -> Kochle and Schneeb...,634,4.3,$4.460 \times 10^{8}$,85.3
6,Kim and Jamieson Table 2 -> Bergfeld et al. (2...,498,3.4,$6.828 \times 10^{7}$,75.4
7,Geldsetzer and Jamieson (2000) -> Bergfeld et ...,475,3.2,$7.164 \times 10^{7}$,76.8
8,Geldsetzer and Jamieson (2000) -> Wautier et a...,449,3.0,$1.681 \times 10^{9}$,45.4
9,Geldsetzer and Jamieson (2000) -> Schottner et...,449,3.0,$7.196 \times 10^{7}$,87.2
10,Kim and Jamieson Table 2 -> Wautier et al. (20...,446,3.0,$1.637 \times 10^{9}$,39.5
11,Kim and Jamieson Table 2 -> Schottner et al. (...,446,3.0,$7.044 \times 10^{7}$,74.5

## Copy-Ready LaTeX Table

In [4]:
print(notebook_latex(top_pathways_table))

\begin{tabular}{lllll}
\toprule
Pathway & Successful slabs & Coverage (%) & Mean D11 (N m) & Mean relative uncertainty (%) \\
\midrule
Kim and Jamieson Table 2 -> Wautier et al. (2015) -> Kochle and Schneebeli (2014) & 743 & 5.0 & $2.219 \times 10^{9}$ & 37.4 \\
Kim and Jamieson Table 2 -> Schottner et al. (2026) -> Kochle and Schneebeli (2014) & 743 & 5.0 & $8.829 \times 10^{7}$ & 73.3 \\
Geldsetzer and Jamieson (2000) -> Wautier et al. (2015) -> Kochle and Schneebeli (2014) & 740 & 5.0 & $2.282 \times 10^{9}$ & 38.2 \\
Geldsetzer and Jamieson (2000) -> Schottner et al. (2026) -> Kochle and Schneebeli (2014) & 740 & 5.0 & $9.024 \times 10^{7}$ & 75.0 \\
Geldsetzer and Jamieson (2000) -> Kochle and Schneebeli (2014) -> Kochle and Schneebeli (2014) & 733 & 5.0 & $4.441 \times 10^{8}$ & 81.9 \\
Kim and Jamieson Table 2 -> Kochle and Schneebeli (2014) -> Kochle and Schneebeli (2014) & 634 & 4.3 & $4.460 \times 10^{8}$ & 85.3 \\
Kim and Jamieson Table 2 -> Bergfeld et al. (2023) -> Kochle and Schneebeli (2014) & 498 & 3.4 & $6.828 \times 10^{7}$ & 75.4 \\
Geldsetzer and Jamieson (2000) -> Bergfeld et al. (2023) -> Kochle and Schneebeli (2014) & 475 & 3.2 & $7.164 \times 10^{7}$ & 76.8 \\
Geldsetzer and Jamieson (2000) -> Wautier et al. (2015) -> Srivastava et al. (2016) & 449 & 3.0 & $1.681 \times 10^{9}$ & 45.4 \\
Geldsetzer and Jamieson (2000) -> Schottner et al. (2026) -> Srivastava et al. (2016) & 449 & 3.0 & $7.196 \times 10^{7}$ & 87.2 \\
Kim and Jamieson Table 2 -> Wautier et al. (2015) -> Srivastava et al. (2016) & 446 & 3.0 & $1.637 \times 10^{9}$ & 39.5 \\
Kim and Jamieson Table 2 -> Schottner et al. (2026) -> Srivastava et al. (2016) & 446 & 3.0 & $7.044 \times 10^{7}$ & 74.5 \\
\bottomrule
\end{tabular}