# Slab Weight Pathway Input Coverage

Analyze ECTP slab coverage for `slab_weight_shear` and `slab_weight_shear_with_elasticity`, then export the paper-ready coverage and attrition figures plus compact tables for the manuscript.

In [1]:
import math
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

from notebook_utils import create_ectp_slabs, hess_rcparams, load_pits
from paper_figure_utils import (
    build_slab_weight_coverage_comparison_figure,
    build_slab_weight_shear_with_elasticity_attrition_figure,
    format_method_path,
    notebook_latex,
    prepare_slab_weight_shear_table,
    prepare_slab_weight_shear_with_elasticity_table,
    save_paper_figure,
)
from snowpyt_mechparams.pathway import find_parameterizations
from snowpyt_mechparams.execution import ExecutionEngine
from snowpyt_mechparams.graph import default_graph

try:
    from tqdm import tqdm
except ImportError:
    def tqdm(items, **_kwargs):
        return items

hess_rcparams()

## Load Data and Enumerate Paths

`slab_weight_shear` coverage is evaluated from density, layer thickness, and slope angle. `slab_weight_shear_with_elasticity` coverage adds Young's modulus and Poisson's ratio availability on every slab layer.

In [2]:
def count_ok(traces, param: str, n_layers: int) -> bool:
    return sum(
        1
        for trace in traces
        if trace.parameter == param
        and trace.layer_index is not None
        and trace.success
        and trace.output is not None
    ) == n_layers


def has_finite_value(value) -> bool:
    if value is None:
        return False
    value = getattr(value, 'n', value)
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False


pits = load_pits()
ectp_slabs = create_ectp_slabs(pits)
total_slabs = len(ectp_slabs)

engine = ExecutionEngine()
shear_paths = find_parameterizations(default_graph, default_graph.get_node('slab_weight_shear'))
elasticity_paths = find_parameterizations(default_graph, default_graph.get_node('slab_weight_shear_with_elasticity'))

print(f'Loaded {len(pits):,} pits and {total_slabs:,} ECTP slabs')
print(f'slab_weight_shear pathways: {len(shear_paths)}')
print(f'slab_weight_shear_with_elasticity pathways: {len(elasticity_paths)}')

Loaded 50,278 pits and 14,776 ECTP slabs
slab_weight_shear pathways: 4
slab_weight_shear_with_elasticity pathways: 32

## Slab Weight_Shear Coverage Summary

In [3]:
shear_records = []

for slab in tqdm(ectp_slabs, desc='slab_weight_shear coverage', unit='slab'):
    results = engine.execute_all(slab, 'slab_weight_shear')
    n_layers = len(slab.layers)
    thickness_ok = all(layer.thickness is not None for layer in slab.layers)
    slope_angle_ok = has_finite_value(slab.angle)

    for pathway in results.pathways.values():
        density_method = pathway.methods_used.get('density', 'data_flow')
        ok_density = count_ok(pathway.computation_trace, 'density', n_layers)
        shear_records.append(
            {
                'slab_id': slab.slab_id,
                'density_method': density_method,
                'slab_density_ok': ok_density,
                'thickness_ok': thickness_ok,
                'slope_angle_ok': slope_angle_ok,
                'all_inputs_ok': ok_density and thickness_ok and slope_angle_ok,
            }
        )

shear_df = pd.DataFrame(shear_records)
shear_cov = (
    shear_df.groupby('density_method')
    .agg(
        n_density_ok=('slab_density_ok', 'sum'),
        n_thickness_ok=('thickness_ok', 'sum'),
        n_slope_angle_ok=('slope_angle_ok', 'sum'),
        n_all_inputs=('all_inputs_ok', 'sum'),
    )
    .reset_index()
    .sort_values('n_all_inputs', ascending=False)
)
shear_table = prepare_slab_weight_shear_table(shear_cov, total_slabs)
shear_table

slab_weight_shear coverage:   0%|          | 0/14776 [00:00<?, ?slab/s]

slab_weight_shear coverage:   3%|▎         | 378/14776 [00:00<00:03, 3774.19slab/s]

slab_weight_shear coverage:   5%|▌         | 785/14776 [00:00<00:03, 3946.99slab/s]

slab_weight_shear coverage:   8%|▊         | 1198/14776 [00:00<00:03, 4027.92slab/s]

slab_weight_shear coverage:  11%|█▏        | 1663/14776 [00:00<00:03, 4269.35slab/s]

slab_weight_shear coverage:  14%|█▍        | 2095/14776 [00:00<00:02, 4286.67slab/s]

slab_weight_shear coverage:  17%|█▋        | 2524/14776 [00:00<00:02, 4233.57slab/s]

slab_weight_shear coverage:  20%|█▉        | 2948/14776 [00:00<00:02, 4215.05slab/s]

slab_weight_shear coverage:  23%|██▎       | 3397/14776 [00:00<00:02, 4300.65slab/s]

slab_weight_shear coverage:  26%|██▌       | 3828/14776 [00:00<00:02, 4242.44slab/s]

slab_weight_shear coverage:  29%|██▉       | 4253/14776 [00:01<00:02, 4180.42slab/s]

slab_weight_shear coverage:  32%|███▏      | 4672/14776 [00:01<00:02, 4099.71slab/s]

slab_weight_shear coverage:  35%|███▍      | 5102/14776 [00:01<00:02, 4158.48slab/s]

slab_weight_shear coverage:  37%|███▋      | 5531/14776 [00:01<00:02, 4195.21slab/s]

slab_weight_shear coverage:  40%|████      | 5951/14776 [00:01<00:02, 4157.44slab/s]

slab_weight_shear coverage:  43%|████▎     | 6376/14776 [00:01<00:02, 4182.16slab/s]

slab_weight_shear coverage:  46%|████▌     | 6795/14776 [00:01<00:01, 4183.08slab/s]

slab_weight_shear coverage:  49%|████▉     | 7233/14776 [00:01<00:01, 4239.93slab/s]

slab_weight_shear coverage:  52%|█████▏    | 7658/14776 [00:01<00:01, 4177.26slab/s]

slab_weight_shear coverage:  55%|█████▍    | 8077/14776 [00:01<00:01, 4057.93slab/s]

slab_weight_shear coverage:  58%|█████▊    | 8509/14776 [00:02<00:01, 4129.85slab/s]

slab_weight_shear coverage:  60%|██████    | 8930/14776 [00:02<00:01, 4152.56slab/s]

slab_weight_shear coverage:  63%|██████▎   | 9380/14776 [00:02<00:01, 4254.00slab/s]

slab_weight_shear coverage:  66%|██████▋   | 9806/14776 [00:02<00:01, 4215.12slab/s]

slab_weight_shear coverage:  69%|██████▉   | 10228/14776 [00:02<00:01, 4138.18slab/s]

slab_weight_shear coverage:  72%|███████▏  | 10643/14776 [00:02<00:01, 4110.94slab/s]

slab_weight_shear coverage:  75%|███████▍  | 11055/14776 [00:02<00:00, 4070.26slab/s]

slab_weight_shear coverage:  78%|███████▊  | 11467/14776 [00:02<00:00, 4083.21slab/s]

slab_weight_shear coverage:  80%|████████  | 11876/14776 [00:02<00:00, 3992.12slab/s]

slab_weight_shear coverage:  83%|████████▎ | 12333/14776 [00:02<00:00, 4159.52slab/s]

slab_weight_shear coverage:  87%|████████▋ | 12794/14776 [00:03<00:00, 4290.60slab/s]

slab_weight_shear coverage:  90%|████████▉ | 13231/14776 [00:03<00:00, 4312.50slab/s]

slab_weight_shear coverage:  93%|█████████▎| 13674/14776 [00:03<00:00, 4346.19slab/s]

slab_weight_shear coverage:  96%|█████████▌| 14112/14776 [00:03<00:00, 4356.15slab/s]

slab_weight_shear coverage:  98%|█████████▊| 14548/14776 [00:03<00:00, 4281.58slab/s]

slab_weight_shear coverage: 100%|██████████| 14776/14776 [00:03<00:00, 4191.19slab/s]

                            Density method Successful slabs Coverage (%)
2          Kim and Jamieson (2014) Table 2            5,470         37.0
1           Geldsetzer and Jamieson (2000)            4,187         28.3
3  Kim and Jamieson (2014) Eq. 5 / Table 6              697          4.7
0                   Direct matched density              109          0.7

## Slab Weight_Shear With Elasticity Coverage, Attrition, and Figure Export

In [4]:
elasticity_records = []

for slab in tqdm(ectp_slabs, desc='slab_weight_shear_with_elasticity coverage', unit='slab'):
    results = engine.execute_all(slab, 'slab_weight_shear_with_elasticity')
    n_layers = len(slab.layers)
    thickness_ok = all(layer.thickness is not None for layer in slab.layers)
    slope_angle_ok = has_finite_value(slab.angle)

    for pathway in results.pathways.values():
        methods = pathway.methods_used
        density_method = methods.get('density', 'data_flow')
        emod_method = methods.get('elastic_modulus', '?')
        nu_method = methods.get('poissons_ratio', '?')

        ok_density = count_ok(pathway.computation_trace, 'density', n_layers)
        ok_emod = count_ok(pathway.computation_trace, 'elastic_modulus', n_layers)
        ok_nu = count_ok(pathway.computation_trace, 'poissons_ratio', n_layers)

        elasticity_records.append(
            {
                'slab_id': slab.slab_id,
                'density_method': density_method,
                'emod_method': emod_method,
                'nu_method': nu_method,
                'ok_density': ok_density,
                'ok_thickness': thickness_ok,
                'ok_slope_angle': slope_angle_ok,
                'ok_emod': ok_emod,
                'ok_nu': ok_nu,
                'all_inputs_ok': ok_density and thickness_ok and slope_angle_ok and ok_emod and ok_nu,
            }
        )

elasticity_df = pd.DataFrame(elasticity_records)
elasticity_cov = (
    elasticity_df.groupby(['density_method', 'emod_method', 'nu_method'])
    .agg(
        n_density_ok=('ok_density', 'sum'),
        n_thickness_ok=('ok_thickness', 'sum'),
        n_slope_angle_ok=('ok_slope_angle', 'sum'),
        n_emod_ok=('ok_emod', 'sum'),
        n_nu_ok=('ok_nu', 'sum'),
        n_all_inputs=('all_inputs_ok', 'sum'),
    )
    .reset_index()
    .sort_values('n_all_inputs', ascending=False)
)

best_density = 'kim_jamieson_table2'
best_emod = 'wautier'
best_nu = 'kochle'
best_subset = elasticity_df[
    (elasticity_df['density_method'] == best_density)
    & (elasticity_df['emod_method'] == best_emod)
    & (elasticity_df['nu_method'] == best_nu)
].copy()

ok_shear_inputs = (
    best_subset['ok_density']
    & best_subset['ok_thickness']
    & best_subset['ok_slope_angle']
)
attrition_steps = [
    ('', total_slabs),
    (r'$\rho$ valid', int(best_subset['ok_density'].sum())),
    (r'$\rho + h_n + \psi$ valid', int(ok_shear_inputs.sum())),
    (r'$\rho + h_n + \psi + E$ valid', int((ok_shear_inputs & best_subset['ok_emod']).sum())),
    (r'$\rho + h_n + \psi + E + \nu$ valid', int(best_subset['all_inputs_ok'].sum())),
]
attrition_methods = [
    '',
    r'$\rho$ method: Kim T2',
    r'$h_n$, $\psi$ valid',
    r'$E$ method: Wautier',
    r'$\nu$ method: Köchle',
]

coverage_paths = save_paper_figure(
    build_slab_weight_coverage_comparison_figure(shear_cov, elasticity_cov, total_slabs, top_n=10),
    'slab_weight_coverage_comparison',
    close=True,
)
attrition_paths = save_paper_figure(
    build_slab_weight_shear_with_elasticity_attrition_figure(
        attrition_steps,
        total_slabs,
        format_method_path(best_density, best_emod, best_nu, short=True),
        method_steps=attrition_methods,
    ),
    'slab_weight_shear_with_elasticity_attrition',
    close=True,
)

elasticity_table = prepare_slab_weight_shear_with_elasticity_table(elasticity_cov, total_slabs, top_n=8)
print('Coverage figure exports:', coverage_paths)
print('Attrition figure exports:', attrition_paths)
elasticity_table

slab_weight_shear_with_elasticity coverage:   0%|          | 0/14776 [00:00<?, ?slab/s]

slab_weight_shear_with_elasticity coverage:   0%|          | 38/14776 [00:00<00:40, 362.02slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 75/14776 [00:00<00:41, 350.85slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 111/14776 [00:00<00:43, 340.07slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 150/14776 [00:00<00:41, 353.66slab/s]

slab_weight_shear_with_elasticity coverage:   1%|▏         | 186/14776 [00:00<00:42, 340.24slab/s]

slab_weight_shear_with_elasticity coverage:   1%|▏         | 221/14776 [00:00<00:44, 330.58slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 255/14776 [00:00<00:45, 322.28slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 290/14776 [00:00<00:43, 329.35slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 325/14776 [00:00<00:43, 332.55slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 359/14776 [00:01<00:43, 331.75slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 393/14776 [00:01<00:44, 324.34slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 426/14776 [00:01<00:46, 309.25slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 458/14776 [00:01<00:47, 304.07slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 490/14776 [00:01<00:46, 308.04slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▎         | 524/14776 [00:01<00:44, 317.04slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 558/14776 [00:01<00:44, 319.91slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 593/14776 [00:01<00:43, 326.29slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 626/14776 [00:01<00:44, 315.37slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 658/14776 [00:02<00:45, 310.43slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▍         | 699/14776 [00:02<00:41, 337.18slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▍         | 733/14776 [00:02<00:43, 321.95slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▌         | 766/14776 [00:02<00:44, 317.58slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▌         | 798/14776 [00:02<00:44, 317.17slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 830/14776 [00:02<00:44, 311.87slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 864/14776 [00:02<00:43, 318.62slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 898/14776 [00:02<00:43, 322.28slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▋         | 931/14776 [00:02<00:44, 313.38slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 966/14776 [00:02<00:42, 323.58slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 999/14776 [00:03<00:44, 312.19slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 1031/14776 [00:03<00:44, 308.26slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 1062/14776 [00:03<00:45, 302.79slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 1093/14776 [00:03<00:45, 302.78slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1124/14776 [00:03<00:45, 297.36slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1156/14776 [00:03<00:44, 303.66slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1195/14776 [00:03<00:41, 328.73slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1234/14776 [00:03<00:39, 345.21slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▊         | 1269/14776 [00:03<00:39, 339.78slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1304/14776 [00:04<00:39, 339.91slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1339/14776 [00:04<00:39, 341.94slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1379/14776 [00:04<00:37, 358.20slab/s]

slab_weight_shear_with_elasticity coverage:  10%|▉         | 1420/14776 [00:04<00:35, 372.13slab/s]

slab_weight_shear_with_elasticity coverage:  10%|▉         | 1458/14776 [00:04<00:36, 368.16slab/s]

slab_weight_shear_with_elasticity coverage:  10%|█         | 1495/14776 [00:04<00:36, 366.75slab/s]

slab_weight_shear_with_elasticity coverage:  10%|█         | 1532/14776 [00:04<00:36, 361.80slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1569/14776 [00:04<00:37, 351.76slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1605/14776 [00:04<00:38, 345.70slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1640/14776 [00:04<00:37, 346.09slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█▏        | 1675/14776 [00:05<00:38, 340.16slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1710/14776 [00:05<00:38, 342.62slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1745/14776 [00:05<00:38, 335.74slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1779/14776 [00:05<00:40, 319.05slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1814/14776 [00:05<00:39, 327.01slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1848/14776 [00:05<00:39, 328.90slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1882/14776 [00:05<00:39, 327.16slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1916/14776 [00:05<00:39, 328.28slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1949/14776 [00:05<00:40, 318.51slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1983/14776 [00:06<00:39, 324.49slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▎        | 2016/14776 [00:06<00:39, 325.46slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2049/14776 [00:06<00:40, 316.70slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2081/14776 [00:06<00:40, 316.79slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2113/14776 [00:06<00:40, 311.98slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▍        | 2145/14776 [00:06<00:44, 281.80slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▍        | 2174/14776 [00:06<00:47, 266.30slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▍        | 2202/14776 [00:06<00:46, 267.86slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▌        | 2233/14776 [00:06<00:44, 279.17slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▌        | 2269/14776 [00:07<00:41, 300.30slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2300/14776 [00:07<00:41, 301.79slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2334/14776 [00:07<00:39, 311.74slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2366/14776 [00:07<00:40, 305.27slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2399/14776 [00:07<00:39, 311.82slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▋        | 2431/14776 [00:07<00:39, 309.56slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2463/14776 [00:07<00:40, 306.27slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2500/14776 [00:07<00:38, 322.82slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2535/14776 [00:07<00:37, 325.63slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2568/14776 [00:07<00:37, 322.99slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2601/14776 [00:08<00:37, 320.72slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2635/14776 [00:08<00:37, 323.42slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2668/14776 [00:08<00:39, 307.09slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2705/14776 [00:08<00:37, 324.70slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▊        | 2738/14776 [00:08<00:38, 313.47slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2772/14776 [00:08<00:37, 319.65slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2812/14776 [00:08<00:35, 341.80slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2847/14776 [00:08<00:35, 340.37slab/s]

slab_weight_shear_with_elasticity coverage:  20%|█▉        | 2882/14776 [00:08<00:36, 329.28slab/s]

slab_weight_shear_with_elasticity coverage:  20%|█▉        | 2916/14776 [00:09<00:36, 322.83slab/s]

slab_weight_shear_with_elasticity coverage:  20%|█▉        | 2949/14776 [00:09<00:36, 322.98slab/s]

slab_weight_shear_with_elasticity coverage:  20%|██        | 2982/14776 [00:09<00:36, 322.63slab/s]

slab_weight_shear_with_elasticity coverage:  20%|██        | 3015/14776 [00:09<00:38, 302.27slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██        | 3054/14776 [00:09<00:36, 325.10slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██        | 3090/14776 [00:09<00:35, 331.14slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██        | 3124/14776 [00:09<00:39, 292.44slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██▏       | 3155/14776 [00:09<00:54, 211.51slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3182/14776 [00:10<00:52, 222.55slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3223/14776 [00:10<00:43, 265.05slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3262/14776 [00:10<00:39, 294.21slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3298/14776 [00:10<00:36, 310.74slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3332/14776 [00:10<00:35, 318.20slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3367/14776 [00:10<00:35, 325.38slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3401/14776 [00:10<00:34, 328.17slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3439/14776 [00:10<00:33, 339.55slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▎       | 3474/14776 [00:10<00:34, 326.17slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▎       | 3508/14776 [00:11<00:34, 328.20slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3542/14776 [00:11<00:34, 327.85slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3576/14776 [00:11<00:34, 326.38slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3609/14776 [00:11<00:34, 321.92slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▍       | 3642/14776 [00:11<00:34, 319.24slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▍       | 3675/14776 [00:11<00:36, 307.39slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▌       | 3706/14776 [00:11<00:37, 296.56slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▌       | 3737/14776 [00:11<00:37, 297.85slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▌       | 3767/14776 [00:11<00:37, 293.70slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3800/14776 [00:11<00:36, 303.23slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3831/14776 [00:12<00:36, 296.28slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3861/14776 [00:12<00:36, 296.79slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▋       | 3892/14776 [00:12<00:36, 299.25slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 3922/14776 [00:12<00:38, 285.32slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 3954/14776 [00:12<00:37, 288.21slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 3989/14776 [00:12<00:35, 303.69slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 4020/14776 [00:12<00:35, 301.20slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 4057/14776 [00:12<00:33, 319.25slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4092/14776 [00:12<00:32, 324.70slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4125/14776 [00:13<00:32, 322.76slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4158/14776 [00:13<00:33, 317.98slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4194/14776 [00:13<00:32, 327.57slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▊       | 4227/14776 [00:13<00:33, 314.42slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4259/14776 [00:13<00:34, 307.28slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4290/14776 [00:13<00:34, 307.07slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4322/14776 [00:13<00:33, 310.17slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4356/14776 [00:13<00:32, 316.79slab/s]

slab_weight_shear_with_elasticity coverage:  30%|██▉       | 4388/14776 [00:13<00:34, 302.88slab/s]

slab_weight_shear_with_elasticity coverage:  30%|██▉       | 4420/14776 [00:13<00:33, 307.23slab/s]

slab_weight_shear_with_elasticity coverage:  30%|███       | 4451/14776 [00:14<00:34, 303.32slab/s]

slab_weight_shear_with_elasticity coverage:  30%|███       | 4483/14776 [00:14<00:33, 307.21slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4514/14776 [00:14<00:35, 288.77slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4544/14776 [00:14<00:35, 287.31slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4573/14776 [00:14<00:36, 281.88slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4604/14776 [00:14<00:35, 286.98slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███▏      | 4633/14776 [00:14<00:35, 287.12slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4662/14776 [00:14<00:36, 275.15slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4694/14776 [00:14<00:35, 285.22slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4723/14776 [00:15<00:35, 285.48slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4757/14776 [00:15<00:33, 300.13slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4788/14776 [00:15<01:26, 115.66slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4822/14776 [00:15<01:08, 145.55slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4852/14776 [00:16<00:58, 170.63slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4890/14776 [00:16<00:47, 209.50slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4920/14776 [00:16<00:44, 222.84slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▎      | 4951/14776 [00:16<00:40, 242.34slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 4988/14776 [00:16<00:36, 271.44slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 5025/14776 [00:16<00:32, 296.77slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 5059/14776 [00:16<00:31, 305.44slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 5093/14776 [00:16<00:31, 309.43slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▍      | 5126/14776 [00:16<00:30, 312.29slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▍      | 5164/14776 [00:16<00:29, 330.74slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▌      | 5209/14776 [00:17<00:26, 363.25slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5247/14776 [00:17<00:26, 364.26slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5284/14776 [00:17<00:26, 355.56slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5320/14776 [00:17<00:26, 350.56slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5356/14776 [00:17<00:27, 336.86slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▋      | 5390/14776 [00:17<00:29, 317.61slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5424/14776 [00:17<00:29, 321.91slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5457/14776 [00:17<00:30, 309.28slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5489/14776 [00:17<00:29, 312.17slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5521/14776 [00:18<00:29, 312.42slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5558/14776 [00:18<00:28, 324.70slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5591/14776 [00:18<00:29, 307.90slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5624/14776 [00:18<00:29, 312.54slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5656/14776 [00:18<00:30, 300.00slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5688/14776 [00:18<00:29, 303.77slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▊      | 5722/14776 [00:18<00:28, 313.74slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5754/14776 [00:18<00:29, 307.16slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5785/14776 [00:18<00:29, 300.86slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5819/14776 [00:18<00:29, 308.23slab/s]

slab_weight_shear_with_elasticity coverage:  40%|███▉      | 5850/14776 [00:19<00:29, 304.46slab/s]

slab_weight_shear_with_elasticity coverage:  40%|███▉      | 5882/14776 [00:19<00:28, 308.74slab/s]

slab_weight_shear_with_elasticity coverage:  40%|████      | 5914/14776 [00:19<00:28, 311.08slab/s]

slab_weight_shear_with_elasticity coverage:  40%|████      | 5950/14776 [00:19<00:27, 322.66slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 5988/14776 [00:19<00:25, 338.11slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 6022/14776 [00:19<00:27, 318.35slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 6055/14776 [00:19<00:27, 319.14slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 6090/14776 [00:19<00:26, 326.26slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████▏     | 6123/14776 [00:19<00:26, 324.30slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6162/14776 [00:20<00:25, 338.40slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6197/14776 [00:20<00:25, 336.14slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6236/14776 [00:20<00:24, 349.85slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6272/14776 [00:20<00:25, 337.67slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6306/14776 [00:20<00:25, 327.80slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6339/14776 [00:20<00:25, 325.32slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6372/14776 [00:20<00:26, 319.12slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6404/14776 [00:20<00:35, 238.29slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▎     | 6431/14776 [00:21<00:34, 241.50slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▎     | 6458/14776 [00:21<00:33, 245.74slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6490/14776 [00:21<00:31, 264.29slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6523/14776 [00:21<00:29, 279.90slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6557/14776 [00:21<00:27, 296.21slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▍     | 6588/14776 [00:21<00:27, 298.64slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▍     | 6625/14776 [00:21<00:25, 318.62slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▌     | 6660/14776 [00:21<00:24, 326.82slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▌     | 6694/14776 [00:21<00:24, 326.44slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▌     | 6729/14776 [00:21<00:24, 331.70slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▌     | 6768/14776 [00:22<00:23, 347.45slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▌     | 6805/14776 [00:22<00:22, 352.53slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▋     | 6845/14776 [00:22<00:21, 365.65slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6882/14776 [00:22<00:22, 358.71slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6918/14776 [00:22<00:22, 356.23slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6954/14776 [00:22<00:22, 355.24slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6990/14776 [00:22<00:22, 346.33slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7025/14776 [00:22<00:22, 339.76slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7062/14776 [00:22<00:22, 346.56slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7097/14776 [00:22<00:22, 339.46slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7133/14776 [00:23<00:22, 343.03slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▊     | 7168/14776 [00:23<00:22, 331.26slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▊     | 7202/14776 [00:23<00:23, 328.03slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▉     | 7235/14776 [00:23<00:23, 321.44slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▉     | 7271/14776 [00:23<00:22, 330.08slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▉     | 7305/14776 [00:23<00:23, 323.05slab/s]

slab_weight_shear_with_elasticity coverage:  50%|████▉     | 7338/14776 [00:23<00:23, 321.04slab/s]

slab_weight_shear_with_elasticity coverage:  50%|████▉     | 7373/14776 [00:23<00:22, 328.76slab/s]

slab_weight_shear_with_elasticity coverage:  50%|█████     | 7406/14776 [00:23<00:22, 325.38slab/s]

slab_weight_shear_with_elasticity coverage:  50%|█████     | 7439/14776 [00:24<00:22, 320.35slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7472/14776 [00:24<00:22, 318.81slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7506/14776 [00:24<00:22, 323.84slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7539/14776 [00:24<00:23, 313.69slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7571/14776 [00:24<00:24, 291.08slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████▏    | 7601/14776 [00:24<00:24, 287.94slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7631/14776 [00:25<00:47, 149.99slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7658/14776 [00:25<00:41, 170.10slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7691/14776 [00:25<00:35, 200.85slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7720/14776 [00:25<00:32, 219.60slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7752/14776 [00:25<00:28, 242.37slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7785/14776 [00:25<00:26, 263.39slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7815/14776 [00:25<00:25, 270.51slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7849/14776 [00:25<00:24, 287.71slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7880/14776 [00:25<00:24, 283.14slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▎    | 7910/14776 [00:25<00:24, 276.81slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▎    | 7939/14776 [00:26<00:24, 274.59slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▍    | 7968/14776 [00:26<00:24, 277.33slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▍    | 8002/14776 [00:26<00:23, 289.13slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▍    | 8032/14776 [00:26<00:23, 291.83slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▍    | 8062/14776 [00:26<00:23, 289.05slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▍    | 8092/14776 [00:26<00:23, 289.30slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▍    | 8122/14776 [00:26<00:22, 289.45slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▌    | 8156/14776 [00:26<00:21, 301.63slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▌    | 8193/14776 [00:26<00:20, 319.07slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▌    | 8225/14776 [00:27<00:20, 318.67slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▌    | 8264/14776 [00:27<00:19, 337.21slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▌    | 8298/14776 [00:27<00:19, 326.18slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▋    | 8331/14776 [00:27<00:20, 315.07slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8363/14776 [00:27<00:20, 307.48slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8395/14776 [00:27<00:20, 308.06slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8428/14776 [00:27<00:20, 311.45slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8467/14776 [00:27<00:18, 333.63slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8504/14776 [00:27<00:18, 343.73slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8539/14776 [00:27<00:18, 341.99slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8574/14776 [00:28<00:18, 335.50slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8608/14776 [00:28<00:18, 330.73slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8642/14776 [00:28<00:18, 329.58slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▊    | 8675/14776 [00:28<00:18, 324.55slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▉    | 8710/14776 [00:28<00:18, 329.47slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▉    | 8743/14776 [00:28<00:18, 324.77slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▉    | 8778/14776 [00:28<00:18, 328.59slab/s]

slab_weight_shear_with_elasticity coverage:  60%|█████▉    | 8815/14776 [00:28<00:17, 338.49slab/s]

slab_weight_shear_with_elasticity coverage:  60%|█████▉    | 8849/14776 [00:28<00:17, 331.74slab/s]

slab_weight_shear_with_elasticity coverage:  60%|██████    | 8884/14776 [00:28<00:17, 336.60slab/s]

slab_weight_shear_with_elasticity coverage:  60%|██████    | 8918/14776 [00:29<00:17, 328.81slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 8954/14776 [00:29<00:17, 337.31slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 8988/14776 [00:29<00:17, 333.41slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 9023/14776 [00:29<00:17, 336.91slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████▏   | 9059/14776 [00:29<00:16, 342.95slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9096/14776 [00:29<00:16, 350.51slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9133/14776 [00:29<00:15, 354.00slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9171/14776 [00:29<00:15, 361.62slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9208/14776 [00:29<00:16, 347.46slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9244/14776 [00:30<00:15, 349.56slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9280/14776 [00:30<00:15, 347.15slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9315/14776 [00:30<00:16, 338.00slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9353/14776 [00:30<00:15, 348.06slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▎   | 9395/14776 [00:30<00:14, 367.32slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9432/14776 [00:30<00:14, 362.31slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9469/14776 [00:30<00:15, 345.56slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9504/14776 [00:30<00:15, 337.62slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▍   | 9538/14776 [00:30<00:15, 330.26slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▍   | 9572/14776 [00:31<00:15, 330.23slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▌   | 9606/14776 [00:31<00:15, 328.27slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▌   | 9639/14776 [00:31<00:17, 294.64slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▌   | 9670/14776 [00:31<00:17, 292.85slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▌   | 9702/14776 [00:31<00:17, 298.45slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▌   | 9736/14776 [00:31<00:16, 307.85slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▌   | 9770/14776 [00:31<00:15, 316.96slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▋   | 9802/14776 [00:31<00:15, 314.15slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9834/14776 [00:31<00:15, 315.70slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9866/14776 [00:31<00:15, 307.21slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9897/14776 [00:32<00:16, 299.89slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9928/14776 [00:32<00:16, 292.86slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9958/14776 [00:32<00:16, 287.20slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 9993/14776 [00:32<00:15, 303.08slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10024/14776 [00:32<00:15, 301.24slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10056/14776 [00:32<00:15, 306.08slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10090/14776 [00:32<00:14, 315.13slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▊   | 10122/14776 [00:32<00:15, 303.78slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▊   | 10153/14776 [00:32<00:16, 287.52slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▉   | 10182/14776 [00:33<00:15, 287.71slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▉   | 10211/14776 [00:33<00:29, 156.76slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▉   | 10247/14776 [00:33<00:23, 193.13slab/s]

slab_weight_shear_with_elasticity coverage:  70%|██████▉   | 10282/14776 [00:33<00:19, 224.74slab/s]

slab_weight_shear_with_elasticity coverage:  70%|██████▉   | 10317/14776 [00:33<00:17, 251.23slab/s]

slab_weight_shear_with_elasticity coverage:  70%|███████   | 10352/14776 [00:33<00:16, 273.10slab/s]

slab_weight_shear_with_elasticity coverage:  70%|███████   | 10384/14776 [00:33<00:15, 282.19slab/s]

slab_weight_shear_with_elasticity coverage:  70%|███████   | 10417/14776 [00:34<00:14, 293.93slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10450/14776 [00:34<00:14, 300.98slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10482/14776 [00:34<00:14, 292.46slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10514/14776 [00:34<00:14, 298.61slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████▏  | 10545/14776 [00:34<00:14, 296.68slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10576/14776 [00:34<00:14, 299.91slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10608/14776 [00:34<00:13, 303.84slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10641/14776 [00:34<00:13, 309.35slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10674/14776 [00:34<00:13, 314.30slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10710/14776 [00:34<00:12, 326.51slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10744/14776 [00:35<00:12, 327.83slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10777/14776 [00:35<00:12, 314.21slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10809/14776 [00:35<00:12, 307.78slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10841/14776 [00:35<00:12, 309.21slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▎  | 10873/14776 [00:35<00:13, 290.19slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10903/14776 [00:35<00:13, 289.56slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10933/14776 [00:35<00:13, 278.87slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10962/14776 [00:35<00:14, 272.38slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10992/14776 [00:35<00:13, 277.58slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▍  | 11025/14776 [00:36<00:12, 292.09slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▍  | 11056/14776 [00:36<00:12, 296.78slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▌  | 11088/14776 [00:36<00:12, 301.03slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▌  | 11120/14776 [00:36<00:12, 303.33slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▌  | 11151/14776 [00:36<00:12, 281.78slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11188/14776 [00:36<00:11, 306.01slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11220/14776 [00:36<00:11, 308.20slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11256/14776 [00:36<00:10, 322.76slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▋  | 11290/14776 [00:36<00:10, 325.38slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11324/14776 [00:37<00:10, 328.87slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11360/14776 [00:37<00:10, 337.86slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11394/14776 [00:37<00:10, 312.27slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11432/14776 [00:37<00:10, 329.08slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11466/14776 [00:37<00:10, 324.47slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11502/14776 [00:37<00:09, 334.50slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11536/14776 [00:37<00:09, 324.52slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11569/14776 [00:37<00:10, 311.02slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▊  | 11601/14776 [00:37<00:10, 299.13slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▊  | 11633/14776 [00:38<00:10, 303.56slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11664/14776 [00:38<00:11, 282.73slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11693/14776 [00:38<00:10, 282.22slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11722/14776 [00:38<00:11, 268.57slab/s]

slab_weight_shear_with_elasticity coverage:  80%|███████▉  | 11759/14776 [00:38<00:10, 295.17slab/s]

slab_weight_shear_with_elasticity coverage:  80%|███████▉  | 11789/14776 [00:38<00:10, 293.13slab/s]

slab_weight_shear_with_elasticity coverage:  80%|███████▉  | 11819/14776 [00:38<00:10, 271.81slab/s]

slab_weight_shear_with_elasticity coverage:  80%|████████  | 11851/14776 [00:38<00:10, 282.65slab/s]

slab_weight_shear_with_elasticity coverage:  80%|████████  | 11885/14776 [00:38<00:09, 297.53slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11926/14776 [00:39<00:08, 325.49slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11961/14776 [00:39<00:08, 332.15slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11995/14776 [00:39<00:08, 331.87slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████▏ | 12030/14776 [00:39<00:08, 335.93slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12064/14776 [00:39<00:08, 334.56slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12098/14776 [00:39<00:08, 332.88slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12133/14776 [00:39<00:07, 336.03slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12174/14776 [00:39<00:07, 356.73slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12212/14776 [00:39<00:07, 362.22slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12251/14776 [00:39<00:06, 365.79slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12288/14776 [00:40<00:07, 341.59slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12325/14776 [00:40<00:07, 348.74slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▎ | 12361/14776 [00:40<00:06, 345.02slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▍ | 12397/14776 [00:40<00:06, 348.44slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▍ | 12436/14776 [00:40<00:06, 358.15slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▍ | 12472/14776 [00:40<00:06, 345.86slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▍ | 12507/14776 [00:40<00:06, 344.39slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▍ | 12542/14776 [00:40<00:06, 340.83slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▌ | 12582/14776 [00:40<00:06, 357.43slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▌ | 12621/14776 [00:40<00:05, 365.95slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12658/14776 [00:41<00:05, 353.06slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12695/14776 [00:41<00:05, 355.20slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12731/14776 [00:41<00:05, 352.48slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▋ | 12767/14776 [00:41<00:05, 345.77slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12806/14776 [00:41<00:05, 353.32slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12842/14776 [00:41<00:05, 349.43slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12877/14776 [00:41<00:05, 331.67slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12911/14776 [00:41<00:05, 323.47slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 12944/14776 [00:42<00:12, 152.30slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 12982/14776 [00:42<00:09, 187.79slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 13019/14776 [00:42<00:07, 221.00slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 13051/14776 [00:42<00:07, 238.61slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▊ | 13083/14776 [00:42<00:06, 256.79slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13115/14776 [00:42<00:06, 262.87slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13147/14776 [00:42<00:05, 275.73slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13181/14776 [00:43<00:05, 289.85slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13213/14776 [00:43<00:05, 296.43slab/s]

slab_weight_shear_with_elasticity coverage:  90%|████████▉ | 13248/14776 [00:43<00:04, 310.21slab/s]

slab_weight_shear_with_elasticity coverage:  90%|████████▉ | 13285/14776 [00:43<00:04, 325.82slab/s]

slab_weight_shear_with_elasticity coverage:  90%|█████████ | 13319/14776 [00:43<00:04, 329.10slab/s]

slab_weight_shear_with_elasticity coverage:  90%|█████████ | 13358/14776 [00:43<00:04, 343.87slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████ | 13396/14776 [00:43<00:03, 353.31slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████ | 13432/14776 [00:43<00:03, 347.30slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████ | 13470/14776 [00:43<00:03, 353.54slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████▏| 13506/14776 [00:44<00:03, 352.52slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13542/14776 [00:44<00:03, 335.22slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13576/14776 [00:44<00:03, 328.28slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13613/14776 [00:44<00:03, 338.57slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13648/14776 [00:44<00:03, 336.19slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13685/14776 [00:44<00:03, 341.90slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13720/14776 [00:44<00:03, 314.17slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13754/14776 [00:44<00:03, 320.77slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13794/14776 [00:44<00:02, 341.81slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▎| 13829/14776 [00:44<00:02, 341.06slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▍| 13864/14776 [00:45<00:02, 340.04slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▍| 13902/14776 [00:45<00:02, 349.38slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▍| 13938/14776 [00:45<00:02, 336.54slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▍| 13972/14776 [00:45<00:02, 327.28slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▍| 14006/14776 [00:45<00:02, 330.07slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▌| 14045/14776 [00:45<00:02, 347.10slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▌| 14080/14776 [00:45<00:02, 341.46slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14115/14776 [00:45<00:02, 330.12slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14149/14776 [00:45<00:01, 320.47slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14185/14776 [00:46<00:01, 329.70slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14219/14776 [00:46<00:01, 318.40slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▋| 14251/14776 [00:46<00:01, 306.71slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14282/14776 [00:46<00:01, 292.11slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14312/14776 [00:46<00:01, 290.70slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14342/14776 [00:46<00:01, 288.01slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14381/14776 [00:46<00:01, 315.86slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14413/14776 [00:46<00:01, 307.51slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14444/14776 [00:46<00:01, 306.42slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14478/14776 [00:47<00:00, 313.42slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14515/14776 [00:47<00:00, 327.31slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▊| 14555/14776 [00:47<00:00, 347.73slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▊| 14590/14776 [00:47<00:00, 337.67slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▉| 14624/14776 [00:47<00:00, 337.45slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▉| 14658/14776 [00:47<00:00, 335.29slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▉| 14695/14776 [00:47<00:00, 344.99slab/s]

slab_weight_shear_with_elasticity coverage: 100%|█████████▉| 14731/14776 [00:47<00:00, 344.65slab/s]

slab_weight_shear_with_elasticity coverage: 100%|█████████▉| 14766/14776 [00:47<00:00, 342.00slab/s]

slab_weight_shear_with_elasticity coverage: 100%|██████████| 14776/14776 [00:47<00:00, 308.46slab/s]

Coverage figure exports: {'repo_pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.pdf'), 'repo_png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.png'), 'external_pdf': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_coverage_comparison.pdf'), 'external_png': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_coverage_comparison.png'), 'pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.pdf'), 'png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.png'), 'external_dir': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures')}
Attrition figure exports: {'repo_pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'repo_png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'external_pdf': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'external_png': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'external_dir': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures')}

,Density method,$E$ method,$\nu$ method,Successful slabs,Coverage (%)
22,Kim and Jamieson (2014) Table 2,Wautier et al. (2015),Köchle and Schneebeli (2014),687,4.6
20,Kim and Jamieson (2014) Table 2,Schöttner et al. (2026),Köchle and Schneebeli (2014),687,4.6
12,Geldsetzer and Jamieson (2000),Schöttner et al. (2026),Köchle and Schneebeli (2014),684,4.6
14,Geldsetzer and Jamieson (2000),Wautier et al. (2015),Köchle and Schneebeli (2014),684,4.6
10,Geldsetzer and Jamieson (2000),Köchle and Schneebeli (2014),Köchle and Schneebeli (2014),677,4.6
18,Kim and Jamieson (2014) Table 2,Köchle and Schneebeli (2014),Köchle and Schneebeli (2014),581,3.9
16,Kim and Jamieson (2014) Table 2,Bergfeld et al. (2023),Köchle and Schneebeli (2014),465,3.1
8,Geldsetzer and Jamieson (2000),Bergfeld et al. (2023),Köchle and Schneebeli (2014),443,3.0

## Copy-Ready LaTeX Tables

In [5]:
print('slab_weight_shear table:')
print(notebook_latex(shear_table))
print()
print('slab_weight_shear_with_elasticity table:')
print(notebook_latex(elasticity_table))

slab_weight_shear table:
\begin{tabular}{lll}
\toprule
Density method & Successful slabs & Coverage (%) \\
\midrule
Kim and Jamieson (2014) Table 2 & 5,470 & 37.0 \\
Geldsetzer and Jamieson (2000) & 4,187 & 28.3 \\
Kim and Jamieson (2014) Eq. 5 / Table 6 & 697 & 4.7 \\
Direct matched density & 109 & 0.7 \\
\bottomrule
\end{tabular}


slab_weight_shear_with_elasticity table:
\begin{tabular}{lllll}
\toprule
Density method & $E$ method & $\nu$ method & Successful slabs & Coverage (%) \\
\midrule
Kim and Jamieson (2014) Table 2 & Wautier et al. (2015) & Köchle and Schneebeli (2014) & 687 & 4.6 \\
Kim and Jamieson (2014) Table 2 & Schöttner et al. (2026) & Köchle and Schneebeli (2014) & 687 & 4.6 \\
Geldsetzer and Jamieson (2000) & Schöttner et al. (2026) & Köchle and Schneebeli (2014) & 684 & 4.6 \\
Geldsetzer and Jamieson (2000) & Wautier et al. (2015) & Köchle and Schneebeli (2014) & 684 & 4.6 \\
Geldsetzer and Jamieson (2000) & Köchle and Schneebeli (2014) & Köchle and Schneebeli (2014) & 677 & 4.6 \\
Kim and Jamieson (2014) Table 2 & Köchle and Schneebeli (2014) & Köchle and Schneebeli (2014) & 581 & 3.9 \\
Kim and Jamieson (2014) Table 2 & Bergfeld et al. (2023) & Köchle and Schneebeli (2014) & 465 & 3.1 \\
Geldsetzer and Jamieson (2000) & Bergfeld et al. (2023) & Köchle and Schneebeli (2014) & 443 & 3.0 \\
\bottomrule
\end{tabular}