# Slab Weight Pathway Input Coverage

Analyze ECTP slab coverage for `slab_weight_shear` and `slab_weight_shear_with_elasticity`, then export the paper-ready coverage and attrition figures plus compact tables for the manuscript.

In [1]:
import math
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

from notebook_utils import create_ectp_slabs, hess_rcparams, load_pits
from paper_figure_utils import (
    build_slab_weight_coverage_comparison_figure,
    build_slab_weight_shear_with_elasticity_attrition_figure,
    format_method_path,
    notebook_latex,
    prepare_slab_weight_shear_table,
    prepare_slab_weight_shear_with_elasticity_table,
    save_paper_figure,
)
from snowpyt_mechparams.algorithm import find_parameterizations
from snowpyt_mechparams.execution import ExecutionEngine
from snowpyt_mechparams.graph import graph

try:
    from tqdm import tqdm
except ImportError:
    def tqdm(items, **_kwargs):
        return items

hess_rcparams()

## Load Data and Enumerate Paths

`slab_weight_shear` coverage is evaluated from density, layer thickness, and slope angle. `slab_weight_shear_with_elasticity` coverage adds elastic modulus and Poisson's ratio availability on every slab layer.

In [2]:
def count_ok(traces, param: str, n_layers: int) -> bool:
    return sum(
        1
        for trace in traces
        if trace.parameter == param
        and trace.layer_index is not None
        and trace.success
        and trace.output is not None
    ) == n_layers


def has_finite_value(value) -> bool:
    if value is None:
        return False
    value = getattr(value, 'n', value)
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError):
        return False


pits = load_pits()
ectp_slabs = create_ectp_slabs(pits)
total_slabs = len(ectp_slabs)

engine = ExecutionEngine(graph)
shear_paths = find_parameterizations(graph, graph.get_node('slab_weight_shear'))
elasticity_paths = find_parameterizations(graph, graph.get_node('slab_weight_shear_with_elasticity'))

print(f'Loaded {len(pits):,} pits and {total_slabs:,} ECTP slabs')
print(f'slab_weight_shear pathways: {len(shear_paths)}')
print(f'slab_weight_shear_with_elasticity pathways: {len(elasticity_paths)}')

Loaded 50,278 pits and 14,776 ECTP slabs
slab_weight_shear pathways: 4
slab_weight_shear_with_elasticity pathways: 32

## Slab Weight_Shear Coverage Summary

In [3]:
shear_records = []

for slab in tqdm(ectp_slabs, desc='slab_weight_shear coverage', unit='slab'):
    results = engine.execute_all(slab, 'slab_weight_shear')
    n_layers = len(slab.layers)
    thickness_ok = all(layer.thickness is not None for layer in slab.layers)
    slope_angle_ok = has_finite_value(slab.angle)

    for pathway in results.pathways.values():
        density_method = pathway.methods_used.get('density', 'data_flow')
        ok_density = count_ok(pathway.computation_trace, 'density', n_layers)
        shear_records.append(
            {
                'slab_id': slab.slab_id,
                'density_method': density_method,
                'slab_density_ok': ok_density,
                'thickness_ok': thickness_ok,
                'slope_angle_ok': slope_angle_ok,
                'all_inputs_ok': ok_density and thickness_ok and slope_angle_ok,
            }
        )

shear_df = pd.DataFrame(shear_records)
shear_cov = (
    shear_df.groupby('density_method')
    .agg(
        n_density_ok=('slab_density_ok', 'sum'),
        n_thickness_ok=('thickness_ok', 'sum'),
        n_slope_angle_ok=('slope_angle_ok', 'sum'),
        n_all_inputs=('all_inputs_ok', 'sum'),
    )
    .reset_index()
    .sort_values('n_all_inputs', ascending=False)
)
shear_table = prepare_slab_weight_shear_table(shear_cov, total_slabs)
shear_table

slab_weight_shear coverage:   0%|          | 0/14776 [00:00<?, ?slab/s]

slab_weight_shear coverage:   4%|▎         | 519/14776 [00:00<00:02, 5181.51slab/s]

slab_weight_shear coverage:   7%|▋         | 1038/14776 [00:00<00:02, 5087.04slab/s]

slab_weight_shear coverage:  11%|█         | 1562/14776 [00:00<00:02, 5152.59slab/s]

slab_weight_shear coverage:  14%|█▍        | 2080/14776 [00:00<00:02, 5160.60slab/s]

slab_weight_shear coverage:  18%|█▊        | 2620/14776 [00:00<00:02, 5245.38slab/s]

slab_weight_shear coverage:  21%|██▏       | 3146/14776 [00:00<00:02, 5248.75slab/s]

slab_weight_shear coverage:  25%|██▍       | 3671/14776 [00:00<00:02, 5209.13slab/s]

slab_weight_shear coverage:  28%|██▊       | 4194/14776 [00:00<00:02, 5213.21slab/s]

slab_weight_shear coverage:  32%|███▏      | 4724/14776 [00:00<00:01, 5235.69slab/s]

slab_weight_shear coverage:  36%|███▌      | 5248/14776 [00:01<00:01, 5236.66slab/s]

slab_weight_shear coverage:  39%|███▉      | 5773/14776 [00:01<00:01, 5239.94slab/s]

slab_weight_shear coverage:  43%|████▎     | 6321/14776 [00:01<00:01, 5312.00slab/s]

slab_weight_shear coverage:  46%|████▋     | 6853/14776 [00:01<00:01, 5276.38slab/s]

slab_weight_shear coverage:  50%|████▉     | 7386/14776 [00:01<00:01, 5290.97slab/s]

slab_weight_shear coverage:  54%|█████▎    | 7916/14776 [00:01<00:01, 5277.19slab/s]

slab_weight_shear coverage:  57%|█████▋    | 8444/14776 [00:01<00:01, 5249.82slab/s]

slab_weight_shear coverage:  61%|██████    | 8970/14776 [00:01<00:01, 5203.20slab/s]

slab_weight_shear coverage:  64%|██████▍   | 9491/14776 [00:01<00:01, 5167.91slab/s]

slab_weight_shear coverage:  68%|██████▊   | 10008/14776 [00:01<00:00, 5147.16slab/s]

slab_weight_shear coverage:  71%|███████   | 10523/14776 [00:02<00:00, 5130.90slab/s]

slab_weight_shear coverage:  75%|███████▍  | 11037/14776 [00:02<00:00, 5108.76slab/s]

slab_weight_shear coverage:  78%|███████▊  | 11569/14776 [00:02<00:00, 5169.29slab/s]

slab_weight_shear coverage:  82%|████████▏ | 12087/14776 [00:02<00:00, 5153.20slab/s]

slab_weight_shear coverage:  85%|████████▌ | 12604/14776 [00:02<00:00, 5156.05slab/s]

slab_weight_shear coverage:  89%|████████▉ | 13120/14776 [00:02<00:00, 5150.44slab/s]

slab_weight_shear coverage:  92%|█████████▏| 13644/14776 [00:02<00:00, 5171.14slab/s]

slab_weight_shear coverage:  96%|█████████▌| 14162/14776 [00:02<00:00, 5156.50slab/s]

slab_weight_shear coverage:  99%|█████████▉| 14678/14776 [00:02<00:00, 5102.52slab/s]

slab_weight_shear coverage: 100%|██████████| 14776/14776 [00:02<00:00, 5186.05slab/s]

                   Density method Successful slabs Coverage (%)
2        Kim and Jamieson Table 2            5,470         37.0
1  Geldsetzer and Jamieson (2000)            4,187         28.3
3        Kim and Jamieson Table 5              697          4.7
0          Direct matched density              109          0.7

## Slab Weight_Shear With Elasticity Coverage, Attrition, and Figure Export

In [4]:
elasticity_records = []

for slab in tqdm(ectp_slabs, desc='slab_weight_shear_with_elasticity coverage', unit='slab'):
    results = engine.execute_all(slab, 'slab_weight_shear_with_elasticity')
    n_layers = len(slab.layers)
    thickness_ok = all(layer.thickness is not None for layer in slab.layers)
    slope_angle_ok = has_finite_value(slab.angle)

    for pathway in results.pathways.values():
        methods = pathway.methods_used
        density_method = methods.get('density', 'data_flow')
        emod_method = methods.get('elastic_modulus', '?')
        nu_method = methods.get('poissons_ratio', '?')

        ok_density = count_ok(pathway.computation_trace, 'density', n_layers)
        ok_emod = count_ok(pathway.computation_trace, 'elastic_modulus', n_layers)
        ok_nu = count_ok(pathway.computation_trace, 'poissons_ratio', n_layers)

        elasticity_records.append(
            {
                'slab_id': slab.slab_id,
                'density_method': density_method,
                'emod_method': emod_method,
                'nu_method': nu_method,
                'ok_density': ok_density,
                'ok_thickness': thickness_ok,
                'ok_slope_angle': slope_angle_ok,
                'ok_emod': ok_emod,
                'ok_nu': ok_nu,
                'all_inputs_ok': ok_density and thickness_ok and slope_angle_ok and ok_emod and ok_nu,
            }
        )

elasticity_df = pd.DataFrame(elasticity_records)
elasticity_cov = (
    elasticity_df.groupby(['density_method', 'emod_method', 'nu_method'])
    .agg(
        n_density_ok=('ok_density', 'sum'),
        n_thickness_ok=('ok_thickness', 'sum'),
        n_slope_angle_ok=('ok_slope_angle', 'sum'),
        n_emod_ok=('ok_emod', 'sum'),
        n_nu_ok=('ok_nu', 'sum'),
        n_all_inputs=('all_inputs_ok', 'sum'),
    )
    .reset_index()
    .sort_values('n_all_inputs', ascending=False)
)

best_density = 'kim_jamieson_table2'
best_emod = 'wautier'
best_nu = 'kochle'
best_subset = elasticity_df[
    (elasticity_df['density_method'] == best_density)
    & (elasticity_df['emod_method'] == best_emod)
    & (elasticity_df['nu_method'] == best_nu)
].copy()

ok_shear_inputs = (
    best_subset['ok_density']
    & best_subset['ok_thickness']
    & best_subset['ok_slope_angle']
)
attrition_steps = [
    ('All ECTP slabs', total_slabs),
    ('Density valid for all slab layers', int(best_subset['ok_density'].sum())),
    ('Density + thickness + slope angle valid', int(ok_shear_inputs.sum())),
    ('Density + thickness + slope angle + E valid', int((ok_shear_inputs & best_subset['ok_emod']).sum())),
    ('Density + thickness + slope angle + E + nu valid', int(best_subset['all_inputs_ok'].sum())),
]

coverage_paths = save_paper_figure(
    build_slab_weight_coverage_comparison_figure(shear_cov, elasticity_cov, total_slabs, top_n=12),
    'slab_weight_coverage_comparison',
    close=True,
)
attrition_paths = save_paper_figure(
    build_slab_weight_shear_with_elasticity_attrition_figure(
        attrition_steps,
        total_slabs,
        format_method_path(best_density, best_emod, best_nu, short=True),
    ),
    'slab_weight_shear_with_elasticity_attrition',
    close=True,
)

elasticity_table = prepare_slab_weight_shear_with_elasticity_table(elasticity_cov, total_slabs, top_n=8)
print('Coverage figure exports:', coverage_paths)
print('Attrition figure exports:', attrition_paths)
elasticity_table

slab_weight_shear_with_elasticity coverage:   0%|          | 0/14776 [00:00<?, ?slab/s]

slab_weight_shear_with_elasticity coverage:   0%|          | 43/14776 [00:00<00:35, 417.26slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 93/14776 [00:00<00:31, 462.49slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 140/14776 [00:00<00:34, 423.59slab/s]

slab_weight_shear_with_elasticity coverage:   1%|          | 183/14776 [00:00<00:34, 422.43slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 229/14776 [00:00<00:33, 433.65slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 273/14776 [00:00<00:33, 426.98slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 318/14776 [00:00<00:33, 433.65slab/s]

slab_weight_shear_with_elasticity coverage:   2%|▏         | 369/14776 [00:00<00:31, 453.93slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 415/14776 [00:00<00:33, 434.20slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 459/14776 [00:01<00:33, 425.89slab/s]

slab_weight_shear_with_elasticity coverage:   3%|▎         | 502/14776 [00:01<00:33, 420.22slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▎         | 546/14776 [00:01<00:33, 423.02slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 589/14776 [00:01<00:33, 424.61slab/s]

slab_weight_shear_with_elasticity coverage:   4%|▍         | 632/14776 [00:01<00:34, 407.08slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▍         | 673/14776 [00:01<00:35, 399.43slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▍         | 716/14776 [00:01<00:34, 406.79slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▌         | 759/14776 [00:01<00:33, 412.97slab/s]

slab_weight_shear_with_elasticity coverage:   5%|▌         | 801/14776 [00:01<00:34, 405.43slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 843/14776 [00:02<00:34, 408.02slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 884/14776 [00:02<01:14, 186.16slab/s]

slab_weight_shear_with_elasticity coverage:   6%|▌         | 917/14776 [00:02<01:06, 208.78slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 962/14776 [00:02<00:54, 252.20slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 998/14776 [00:02<00:50, 270.57slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 1040/14776 [00:02<00:45, 304.08slab/s]

slab_weight_shear_with_elasticity coverage:   7%|▋         | 1077/14776 [00:03<00:43, 316.73slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1119/14776 [00:03<00:39, 342.51slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1169/14776 [00:03<00:35, 381.89slab/s]

slab_weight_shear_with_elasticity coverage:   8%|▊         | 1211/14776 [00:03<00:34, 388.19slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▊         | 1259/14776 [00:03<00:32, 412.32slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1307/14776 [00:03<00:31, 429.08slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1352/14776 [00:03<00:31, 428.46slab/s]

slab_weight_shear_with_elasticity coverage:   9%|▉         | 1396/14776 [00:03<00:32, 405.62slab/s]

slab_weight_shear_with_elasticity coverage:  10%|▉         | 1438/14776 [00:03<00:33, 399.51slab/s]

slab_weight_shear_with_elasticity coverage:  10%|█         | 1482/14776 [00:03<00:32, 409.52slab/s]

slab_weight_shear_with_elasticity coverage:  10%|█         | 1530/14776 [00:04<00:30, 429.16slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1574/14776 [00:04<00:32, 411.85slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1619/14776 [00:04<00:31, 418.44slab/s]

slab_weight_shear_with_elasticity coverage:  11%|█         | 1662/14776 [00:04<00:32, 406.74slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1703/14776 [00:04<00:32, 403.21slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1744/14776 [00:04<00:33, 390.43slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1784/14776 [00:04<00:33, 389.14slab/s]

slab_weight_shear_with_elasticity coverage:  12%|█▏        | 1824/14776 [00:04<00:33, 384.84slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1863/14776 [00:04<00:34, 379.15slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1908/14776 [00:05<00:32, 397.50slab/s]

slab_weight_shear_with_elasticity coverage:  13%|█▎        | 1952/14776 [00:05<00:31, 407.11slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▎        | 1995/14776 [00:05<00:31, 412.04slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2037/14776 [00:05<00:31, 408.69slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2078/14776 [00:05<00:34, 364.27slab/s]

slab_weight_shear_with_elasticity coverage:  14%|█▍        | 2118/14776 [00:05<00:33, 373.67slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▍        | 2163/14776 [00:05<00:31, 394.84slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▍        | 2206/14776 [00:05<00:31, 403.04slab/s]

slab_weight_shear_with_elasticity coverage:  15%|█▌        | 2247/14776 [00:05<00:30, 405.02slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2291/14776 [00:06<00:30, 411.55slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2336/14776 [00:06<00:29, 422.74slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▌        | 2379/14776 [00:06<00:29, 413.52slab/s]

slab_weight_shear_with_elasticity coverage:  16%|█▋        | 2426/14776 [00:06<00:28, 428.38slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2470/14776 [00:06<00:29, 412.00slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2515/14776 [00:06<00:29, 420.70slab/s]

slab_weight_shear_with_elasticity coverage:  17%|█▋        | 2563/14776 [00:06<00:27, 437.51slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2610/14776 [00:06<00:27, 445.63slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2655/14776 [00:06<00:29, 417.38slab/s]

slab_weight_shear_with_elasticity coverage:  18%|█▊        | 2698/14776 [00:06<00:29, 407.06slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▊        | 2740/14776 [00:07<00:30, 400.01slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2781/14776 [00:07<00:30, 394.52slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2825/14776 [00:07<00:29, 403.22slab/s]

slab_weight_shear_with_elasticity coverage:  19%|█▉        | 2870/14776 [00:07<00:28, 414.18slab/s]

slab_weight_shear_with_elasticity coverage:  20%|█▉        | 2915/14776 [00:07<00:28, 423.11slab/s]

slab_weight_shear_with_elasticity coverage:  20%|██        | 2964/14776 [00:07<00:26, 441.00slab/s]

slab_weight_shear_with_elasticity coverage:  20%|██        | 3009/14776 [00:07<00:26, 440.80slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██        | 3055/14776 [00:07<00:26, 445.20slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██        | 3105/14776 [00:07<00:25, 460.94slab/s]

slab_weight_shear_with_elasticity coverage:  21%|██▏       | 3152/14776 [00:08<00:26, 444.50slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3197/14776 [00:08<00:26, 438.48slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3243/14776 [00:08<00:25, 444.00slab/s]

slab_weight_shear_with_elasticity coverage:  22%|██▏       | 3288/14776 [00:08<00:25, 442.86slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3333/14776 [00:08<00:28, 407.08slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3379/14776 [00:08<00:27, 421.45slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3422/14776 [00:08<00:27, 406.77slab/s]

slab_weight_shear_with_elasticity coverage:  23%|██▎       | 3466/14776 [00:08<00:27, 414.12slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3512/14776 [00:08<00:26, 426.64slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3555/14776 [00:08<00:27, 415.10slab/s]

slab_weight_shear_with_elasticity coverage:  24%|██▍       | 3597/14776 [00:09<00:27, 409.06slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▍       | 3639/14776 [00:09<00:28, 396.31slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▍       | 3680/14776 [00:09<00:27, 398.82slab/s]

slab_weight_shear_with_elasticity coverage:  25%|██▌       | 3722/14776 [00:09<00:27, 404.16slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3770/14776 [00:09<00:25, 425.19slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3817/14776 [00:09<00:25, 437.37slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▌       | 3861/14776 [00:09<00:25, 432.24slab/s]

slab_weight_shear_with_elasticity coverage:  26%|██▋       | 3909/14776 [00:09<00:24, 446.06slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 3954/14776 [00:09<00:25, 420.60slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 3997/14776 [00:10<00:26, 405.95slab/s]

slab_weight_shear_with_elasticity coverage:  27%|██▋       | 4038/14776 [00:10<00:26, 405.47slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4079/14776 [00:10<00:27, 391.45slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4121/14776 [00:10<00:26, 397.48slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4166/14776 [00:10<00:25, 409.50slab/s]

slab_weight_shear_with_elasticity coverage:  28%|██▊       | 4208/14776 [00:10<00:26, 399.27slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4249/14776 [00:10<00:26, 396.75slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4289/14776 [00:10<00:26, 397.64slab/s]

slab_weight_shear_with_elasticity coverage:  29%|██▉       | 4329/14776 [00:10<00:26, 391.56slab/s]

slab_weight_shear_with_elasticity coverage:  30%|██▉       | 4376/14776 [00:10<00:25, 412.35slab/s]

slab_weight_shear_with_elasticity coverage:  30%|██▉       | 4418/14776 [00:11<00:29, 353.35slab/s]

slab_weight_shear_with_elasticity coverage:  30%|███       | 4458/14776 [00:11<00:28, 360.36slab/s]

slab_weight_shear_with_elasticity coverage:  30%|███       | 4499/14776 [00:11<00:27, 373.67slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4542/14776 [00:11<00:26, 388.95slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███       | 4582/14776 [00:11<00:26, 388.58slab/s]

slab_weight_shear_with_elasticity coverage:  31%|███▏      | 4630/14776 [00:11<00:24, 412.65slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4678/14776 [00:11<00:23, 428.85slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4722/14776 [00:11<00:23, 426.15slab/s]

slab_weight_shear_with_elasticity coverage:  32%|███▏      | 4765/14776 [00:11<00:24, 414.08slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4807/14776 [00:12<00:24, 400.28slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4848/14776 [00:12<00:26, 375.40slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4890/14776 [00:12<00:25, 385.83slab/s]

slab_weight_shear_with_elasticity coverage:  33%|███▎      | 4936/14776 [00:12<00:24, 406.40slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▎      | 4978/14776 [00:12<00:23, 408.97slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 5024/14776 [00:12<00:23, 422.07slab/s]

slab_weight_shear_with_elasticity coverage:  34%|███▍      | 5071/14776 [00:12<00:22, 435.06slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▍      | 5115/14776 [00:12<00:22, 420.91slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▍      | 5158/14776 [00:12<00:23, 404.30slab/s]

slab_weight_shear_with_elasticity coverage:  35%|███▌      | 5200/14776 [00:13<00:23, 408.20slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5247/14776 [00:13<00:22, 425.09slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5296/14776 [00:13<00:21, 438.92slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▌      | 5341/14776 [00:13<00:21, 435.53slab/s]

slab_weight_shear_with_elasticity coverage:  36%|███▋      | 5385/14776 [00:13<00:22, 415.15slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5432/14776 [00:13<00:21, 428.01slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5477/14776 [00:13<00:21, 433.58slab/s]

slab_weight_shear_with_elasticity coverage:  37%|███▋      | 5521/14776 [00:13<00:21, 432.61slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5565/14776 [00:13<00:21, 422.23slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5610/14776 [00:13<00:21, 429.46slab/s]

slab_weight_shear_with_elasticity coverage:  38%|███▊      | 5654/14776 [00:14<00:22, 406.70slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▊      | 5695/14776 [00:14<00:24, 367.12slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5737/14776 [00:14<00:23, 381.06slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5776/14776 [00:14<00:23, 381.59slab/s]

slab_weight_shear_with_elasticity coverage:  39%|███▉      | 5820/14776 [00:14<00:22, 397.14slab/s]

slab_weight_shear_with_elasticity coverage:  40%|███▉      | 5863/14776 [00:14<00:21, 406.17slab/s]

slab_weight_shear_with_elasticity coverage:  40%|███▉      | 5906/14776 [00:14<00:21, 409.77slab/s]

slab_weight_shear_with_elasticity coverage:  40%|████      | 5948/14776 [00:14<00:21, 412.58slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 5993/14776 [00:14<00:20, 423.57slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 6036/14776 [00:15<00:20, 419.63slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████      | 6085/14776 [00:15<00:19, 438.04slab/s]

slab_weight_shear_with_elasticity coverage:  41%|████▏     | 6130/14776 [00:15<00:19, 439.99slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6175/14776 [00:15<00:19, 442.80slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6220/14776 [00:15<00:19, 438.19slab/s]

slab_weight_shear_with_elasticity coverage:  42%|████▏     | 6264/14776 [00:15<00:20, 424.73slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6308/14776 [00:15<00:19, 428.80slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6352/14776 [00:15<00:19, 430.55slab/s]

slab_weight_shear_with_elasticity coverage:  43%|████▎     | 6396/14776 [00:15<00:19, 425.78slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▎     | 6441/14776 [00:15<00:19, 430.12slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6485/14776 [00:16<00:21, 384.38slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6525/14776 [00:16<00:21, 380.10slab/s]

slab_weight_shear_with_elasticity coverage:  44%|████▍     | 6572/14776 [00:16<00:20, 403.47slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▍     | 6615/14776 [00:16<00:19, 408.28slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▌     | 6661/14776 [00:16<00:19, 421.16slab/s]

slab_weight_shear_with_elasticity coverage:  45%|████▌     | 6704/14776 [00:17<00:39, 204.46slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▌     | 6749/14776 [00:17<00:32, 245.18slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▌     | 6790/14776 [00:17<00:28, 275.64slab/s]

slab_weight_shear_with_elasticity coverage:  46%|████▋     | 6835/14776 [00:17<00:25, 311.60slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6877/14776 [00:17<00:23, 334.67slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6919/14776 [00:17<00:22, 354.33slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 6960/14776 [00:17<00:21, 365.11slab/s]

slab_weight_shear_with_elasticity coverage:  47%|████▋     | 7004/14776 [00:17<00:20, 384.63slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7047/14776 [00:17<00:19, 396.25slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7098/14776 [00:17<00:17, 427.24slab/s]

slab_weight_shear_with_elasticity coverage:  48%|████▊     | 7144/14776 [00:18<00:17, 432.07slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▊     | 7189/14776 [00:18<00:17, 436.36slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▉     | 7234/14776 [00:18<00:17, 431.35slab/s]

slab_weight_shear_with_elasticity coverage:  49%|████▉     | 7278/14776 [00:18<00:17, 420.09slab/s]

slab_weight_shear_with_elasticity coverage:  50%|████▉     | 7321/14776 [00:18<00:17, 415.24slab/s]

slab_weight_shear_with_elasticity coverage:  50%|████▉     | 7365/14776 [00:18<00:17, 420.25slab/s]

slab_weight_shear_with_elasticity coverage:  50%|█████     | 7408/14776 [00:18<00:17, 414.43slab/s]

slab_weight_shear_with_elasticity coverage:  50%|█████     | 7452/14776 [00:18<00:17, 420.05slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7495/14776 [00:18<00:17, 407.77slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████     | 7536/14776 [00:18<00:17, 405.37slab/s]

slab_weight_shear_with_elasticity coverage:  51%|█████▏    | 7579/14776 [00:19<00:17, 410.52slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7627/14776 [00:19<00:16, 429.96slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7671/14776 [00:19<00:17, 415.45slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7713/14776 [00:19<00:17, 414.77slab/s]

slab_weight_shear_with_elasticity coverage:  52%|█████▏    | 7755/14776 [00:19<00:17, 412.84slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7797/14776 [00:19<00:17, 401.96slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7838/14776 [00:19<00:17, 403.87slab/s]

slab_weight_shear_with_elasticity coverage:  53%|█████▎    | 7879/14776 [00:19<00:17, 391.63slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▎    | 7927/14776 [00:19<00:16, 416.06slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▍    | 7970/14776 [00:20<00:16, 416.71slab/s]

slab_weight_shear_with_elasticity coverage:  54%|█████▍    | 8012/14776 [00:20<00:16, 417.59slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▍    | 8054/14776 [00:20<00:17, 391.61slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▍    | 8097/14776 [00:20<00:16, 398.62slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▌    | 8138/14776 [00:20<00:17, 388.85slab/s]

slab_weight_shear_with_elasticity coverage:  55%|█████▌    | 8183/14776 [00:20<00:16, 401.90slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▌    | 8224/14776 [00:20<00:16, 403.13slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▌    | 8267/14776 [00:20<00:15, 410.68slab/s]

slab_weight_shear_with_elasticity coverage:  56%|█████▋    | 8314/14776 [00:20<00:15, 426.57slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8357/14776 [00:20<00:15, 419.91slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8400/14776 [00:21<00:15, 410.41slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8446/14776 [00:21<00:14, 423.46slab/s]

slab_weight_shear_with_elasticity coverage:  57%|█████▋    | 8489/14776 [00:21<00:15, 411.38slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8533/14776 [00:21<00:14, 418.24slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8575/14776 [00:21<00:15, 412.77slab/s]

slab_weight_shear_with_elasticity coverage:  58%|█████▊    | 8617/14776 [00:21<00:15, 406.99slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▊    | 8658/14776 [00:21<00:15, 403.90slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▉    | 8705/14776 [00:21<00:14, 420.76slab/s]

slab_weight_shear_with_elasticity coverage:  59%|█████▉    | 8749/14776 [00:21<00:14, 425.28slab/s]

slab_weight_shear_with_elasticity coverage:  60%|█████▉    | 8792/14776 [00:22<00:14, 400.29slab/s]

slab_weight_shear_with_elasticity coverage:  60%|█████▉    | 8833/14776 [00:22<00:15, 390.88slab/s]

slab_weight_shear_with_elasticity coverage:  60%|██████    | 8873/14776 [00:22<00:15, 389.45slab/s]

slab_weight_shear_with_elasticity coverage:  60%|██████    | 8913/14776 [00:22<00:15, 388.46slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 8954/14776 [00:22<00:14, 393.87slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 9002/14776 [00:22<00:13, 418.06slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████    | 9044/14776 [00:22<00:13, 416.60slab/s]

slab_weight_shear_with_elasticity coverage:  61%|██████▏   | 9087/14776 [00:22<00:13, 417.98slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9129/14776 [00:22<00:13, 412.43slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9171/14776 [00:22<00:13, 413.89slab/s]

slab_weight_shear_with_elasticity coverage:  62%|██████▏   | 9213/14776 [00:23<00:13, 411.45slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9255/14776 [00:23<00:13, 408.56slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9301/14776 [00:23<00:13, 419.31slab/s]

slab_weight_shear_with_elasticity coverage:  63%|██████▎   | 9345/14776 [00:23<00:12, 423.19slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▎   | 9388/14776 [00:23<00:12, 416.32slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9430/14776 [00:23<00:13, 408.00slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9471/14776 [00:23<00:13, 403.49slab/s]

slab_weight_shear_with_elasticity coverage:  64%|██████▍   | 9512/14776 [00:23<00:13, 402.84slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▍   | 9553/14776 [00:23<00:13, 396.96slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▍   | 9594/14776 [00:24<00:12, 400.23slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▌   | 9636/14776 [00:24<00:12, 404.30slab/s]

slab_weight_shear_with_elasticity coverage:  65%|██████▌   | 9677/14776 [00:24<00:12, 398.57slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▌   | 9717/14776 [00:24<00:12, 390.82slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▌   | 9758/14776 [00:24<00:12, 394.99slab/s]

slab_weight_shear_with_elasticity coverage:  66%|██████▋   | 9799/14776 [00:24<00:12, 394.49slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9839/14776 [00:24<00:12, 387.08slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9885/14776 [00:24<00:12, 406.70slab/s]

slab_weight_shear_with_elasticity coverage:  67%|██████▋   | 9931/14776 [00:24<00:11, 421.56slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 9974/14776 [00:24<00:11, 419.68slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10017/14776 [00:25<00:11, 409.43slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10059/14776 [00:25<00:11, 402.81slab/s]

slab_weight_shear_with_elasticity coverage:  68%|██████▊   | 10103/14776 [00:25<00:11, 412.65slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▊   | 10145/14776 [00:25<00:11, 401.11slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▉   | 10186/14776 [00:25<00:11, 398.13slab/s]

slab_weight_shear_with_elasticity coverage:  69%|██████▉   | 10229/14776 [00:25<00:11, 406.23slab/s]

slab_weight_shear_with_elasticity coverage:  70%|██████▉   | 10270/14776 [00:25<00:11, 398.97slab/s]

slab_weight_shear_with_elasticity coverage:  70%|██████▉   | 10310/14776 [00:25<00:11, 396.99slab/s]

slab_weight_shear_with_elasticity coverage:  70%|███████   | 10353/14776 [00:25<00:10, 404.41slab/s]

slab_weight_shear_with_elasticity coverage:  70%|███████   | 10395/14776 [00:26<00:10, 407.65slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10437/14776 [00:26<00:10, 410.39slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10479/14776 [00:26<00:10, 406.51slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████   | 10522/14776 [00:26<00:10, 412.40slab/s]

slab_weight_shear_with_elasticity coverage:  71%|███████▏  | 10564/14776 [00:26<00:10, 411.76slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10606/14776 [00:26<00:10, 387.68slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10652/14776 [00:26<00:10, 406.31slab/s]

slab_weight_shear_with_elasticity coverage:  72%|███████▏  | 10693/14776 [00:26<00:10, 402.26slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10734/14776 [00:26<00:10, 385.03slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10783/14776 [00:26<00:09, 413.27slab/s]

slab_weight_shear_with_elasticity coverage:  73%|███████▎  | 10829/14776 [00:27<00:09, 424.90slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▎  | 10872/14776 [00:27<00:09, 402.02slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10913/14776 [00:27<00:09, 395.88slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10956/14776 [00:27<00:09, 404.13slab/s]

slab_weight_shear_with_elasticity coverage:  74%|███████▍  | 10998/14776 [00:27<00:09, 407.69slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▍  | 11039/14776 [00:27<00:09, 404.15slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▌  | 11086/14776 [00:27<00:08, 423.20slab/s]

slab_weight_shear_with_elasticity coverage:  75%|███████▌  | 11129/14776 [00:27<00:08, 412.08slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11173/14776 [00:27<00:08, 419.03slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11216/14776 [00:28<00:08, 414.37slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▌  | 11258/14776 [00:28<00:08, 410.75slab/s]

slab_weight_shear_with_elasticity coverage:  76%|███████▋  | 11301/14776 [00:28<00:08, 415.83slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11343/14776 [00:28<00:08, 415.02slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11387/14776 [00:28<00:08, 422.01slab/s]

slab_weight_shear_with_elasticity coverage:  77%|███████▋  | 11430/14776 [00:28<00:08, 412.53slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11475/14776 [00:28<00:07, 421.26slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11519/14776 [00:28<00:07, 422.78slab/s]

slab_weight_shear_with_elasticity coverage:  78%|███████▊  | 11565/14776 [00:28<00:07, 432.91slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▊  | 11609/14776 [00:28<00:07, 415.11slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11654/14776 [00:29<00:07, 424.60slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11697/14776 [00:29<00:08, 348.46slab/s]

slab_weight_shear_with_elasticity coverage:  79%|███████▉  | 11739/14776 [00:29<00:08, 365.43slab/s]

slab_weight_shear_with_elasticity coverage:  80%|███████▉  | 11782/14776 [00:29<00:07, 381.08slab/s]

slab_weight_shear_with_elasticity coverage:  80%|████████  | 11824/14776 [00:29<00:07, 390.10slab/s]

slab_weight_shear_with_elasticity coverage:  80%|████████  | 11865/14776 [00:29<00:07, 391.53slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11905/14776 [00:29<00:07, 387.91slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11945/14776 [00:29<00:07, 384.87slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████  | 11984/14776 [00:29<00:07, 376.65slab/s]

slab_weight_shear_with_elasticity coverage:  81%|████████▏ | 12027/14776 [00:30<00:07, 391.58slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12069/14776 [00:30<00:06, 397.77slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12109/14776 [00:30<00:06, 392.83slab/s]

slab_weight_shear_with_elasticity coverage:  82%|████████▏ | 12154/14776 [00:30<00:06, 407.39slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12197/14776 [00:30<00:06, 411.27slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12239/14776 [00:30<00:06, 407.31slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12280/14776 [00:30<00:06, 394.87slab/s]

slab_weight_shear_with_elasticity coverage:  83%|████████▎ | 12323/14776 [00:30<00:06, 403.69slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▎ | 12366/14776 [00:30<00:05, 409.42slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▍ | 12408/14776 [00:31<00:05, 402.44slab/s]

slab_weight_shear_with_elasticity coverage:  84%|████████▍ | 12449/14776 [00:31<00:05, 396.17slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▍ | 12490/14776 [00:31<00:05, 399.27slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▍ | 12531/14776 [00:31<00:05, 401.36slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▌ | 12572/14776 [00:31<00:05, 394.79slab/s]

slab_weight_shear_with_elasticity coverage:  85%|████████▌ | 12612/14776 [00:31<00:10, 197.98slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12656/14776 [00:31<00:08, 239.39slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12693/14776 [00:32<00:07, 264.59slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▌ | 12738/14776 [00:32<00:06, 303.93slab/s]

slab_weight_shear_with_elasticity coverage:  86%|████████▋ | 12781/14776 [00:32<00:05, 332.73slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12822/14776 [00:32<00:05, 351.64slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12864/14776 [00:32<00:05, 368.28slab/s]

slab_weight_shear_with_elasticity coverage:  87%|████████▋ | 12905/14776 [00:32<00:04, 376.92slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 12947/14776 [00:32<00:04, 388.74slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 12993/14776 [00:32<00:04, 405.14slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 13035/14776 [00:32<00:04, 399.51slab/s]

slab_weight_shear_with_elasticity coverage:  88%|████████▊ | 13076/14776 [00:32<00:04, 397.95slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13117/14776 [00:33<00:04, 393.87slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13157/14776 [00:33<00:04, 383.59slab/s]

slab_weight_shear_with_elasticity coverage:  89%|████████▉ | 13198/14776 [00:33<00:04, 387.44slab/s]

slab_weight_shear_with_elasticity coverage:  90%|████████▉ | 13238/14776 [00:33<00:03, 390.41slab/s]

slab_weight_shear_with_elasticity coverage:  90%|████████▉ | 13283/14776 [00:33<00:03, 406.00slab/s]

slab_weight_shear_with_elasticity coverage:  90%|█████████ | 13326/14776 [00:33<00:03, 411.43slab/s]

slab_weight_shear_with_elasticity coverage:  90%|█████████ | 13368/14776 [00:33<00:03, 394.90slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████ | 13416/14776 [00:33<00:03, 418.52slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████ | 13459/14776 [00:33<00:03, 413.02slab/s]

slab_weight_shear_with_elasticity coverage:  91%|█████████▏| 13501/14776 [00:34<00:03, 414.99slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13543/14776 [00:34<00:02, 413.66slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13588/14776 [00:34<00:02, 423.86slab/s]

slab_weight_shear_with_elasticity coverage:  92%|█████████▏| 13631/14776 [00:34<00:02, 422.92slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13674/14776 [00:34<00:02, 418.17slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13716/14776 [00:34<00:02, 418.66slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13758/14776 [00:34<00:02, 394.29slab/s]

slab_weight_shear_with_elasticity coverage:  93%|█████████▎| 13801/14776 [00:34<00:02, 401.55slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▎| 13844/14776 [00:34<00:02, 407.65slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▍| 13885/14776 [00:34<00:02, 398.27slab/s]

slab_weight_shear_with_elasticity coverage:  94%|█████████▍| 13927/14776 [00:35<00:02, 403.01slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▍| 13968/14776 [00:35<00:02, 387.14slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▍| 14014/14776 [00:35<00:01, 406.39slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▌| 14055/14776 [00:35<00:01, 404.01slab/s]

slab_weight_shear_with_elasticity coverage:  95%|█████████▌| 14098/14776 [00:35<00:01, 410.21slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14140/14776 [00:35<00:01, 407.41slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▌| 14181/14776 [00:35<00:01, 399.75slab/s]

slab_weight_shear_with_elasticity coverage:  96%|█████████▋| 14224/14776 [00:35<00:01, 405.20slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14269/14776 [00:35<00:01, 416.63slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14311/14776 [00:36<00:01, 417.29slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14353/14776 [00:36<00:01, 406.90slab/s]

slab_weight_shear_with_elasticity coverage:  97%|█████████▋| 14400/14776 [00:36<00:00, 420.86slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14443/14776 [00:36<00:00, 406.21slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14486/14776 [00:36<00:00, 412.16slab/s]

slab_weight_shear_with_elasticity coverage:  98%|█████████▊| 14528/14776 [00:36<00:00, 398.50slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▊| 14569/14776 [00:36<00:00, 388.42slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▉| 14612/14776 [00:36<00:00, 399.26slab/s]

slab_weight_shear_with_elasticity coverage:  99%|█████████▉| 14661/14776 [00:36<00:00, 423.50slab/s]

slab_weight_shear_with_elasticity coverage: 100%|█████████▉| 14708/14776 [00:36<00:00, 436.42slab/s]

slab_weight_shear_with_elasticity coverage: 100%|█████████▉| 14752/14776 [00:37<00:00, 429.29slab/s]

slab_weight_shear_with_elasticity coverage: 100%|██████████| 14776/14776 [00:37<00:00, 397.52slab/s]

Coverage figure exports: {'repo_pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.pdf'), 'repo_png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.png'), 'external_pdf': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_coverage_comparison.pdf'), 'external_png': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_coverage_comparison.png'), 'pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.pdf'), 'png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_coverage_comparison.png'), 'external_dir': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures')}
Attrition figure exports: {'repo_pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'repo_png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'external_pdf': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'external_png': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'pdf': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.pdf'), 'png': PosixPath('/Users/marykate/Desktop/Snow/SnowPyt-MechParams/paper/figures/slab_weight_shear_with_elasticity_attrition.png'), 'external_dir': PosixPath('/Users/marykate/Desktop/Snow/mech_params_paper/figures')}

,Density method,E method,nu method,Successful slabs,Coverage (%)
22,Kim and Jamieson Table 2,Wautier et al. (2015),Kochle and Schneebeli (2014),687,4.6
20,Kim and Jamieson Table 2,Schottner et al. (2026),Kochle and Schneebeli (2014),687,4.6
12,Geldsetzer and Jamieson (2000),Schottner et al. (2026),Kochle and Schneebeli (2014),684,4.6
14,Geldsetzer and Jamieson (2000),Wautier et al. (2015),Kochle and Schneebeli (2014),684,4.6
10,Geldsetzer and Jamieson (2000),Kochle and Schneebeli (2014),Kochle and Schneebeli (2014),677,4.6
18,Kim and Jamieson Table 2,Kochle and Schneebeli (2014),Kochle and Schneebeli (2014),581,3.9
16,Kim and Jamieson Table 2,Bergfeld et al. (2023),Kochle and Schneebeli (2014),465,3.1
8,Geldsetzer and Jamieson (2000),Bergfeld et al. (2023),Kochle and Schneebeli (2014),443,3.0

## Copy-Ready LaTeX Tables

In [5]:
print('slab_weight_shear table:')
print(notebook_latex(shear_table))
print()
print('slab_weight_shear_with_elasticity table:')
print(notebook_latex(elasticity_table))

slab_weight_shear table:
\begin{tabular}{lll}
\toprule
Density method & Successful slabs & Coverage (%) \\
\midrule
Kim and Jamieson Table 2 & 5,470 & 37.0 \\
Geldsetzer and Jamieson (2000) & 4,187 & 28.3 \\
Kim and Jamieson Table 5 & 697 & 4.7 \\
Direct matched density & 109 & 0.7 \\
\bottomrule
\end{tabular}


slab_weight_shear_with_elasticity table:
\begin{tabular}{lllll}
\toprule
Density method & E method & nu method & Successful slabs & Coverage (%) \\
\midrule
Kim and Jamieson Table 2 & Wautier et al. (2015) & Kochle and Schneebeli (2014) & 687 & 4.6 \\
Kim and Jamieson Table 2 & Schottner et al. (2026) & Kochle and Schneebeli (2014) & 687 & 4.6 \\
Geldsetzer and Jamieson (2000) & Schottner et al. (2026) & Kochle and Schneebeli (2014) & 684 & 4.6 \\
Geldsetzer and Jamieson (2000) & Wautier et al. (2015) & Kochle and Schneebeli (2014) & 684 & 4.6 \\
Geldsetzer and Jamieson (2000) & Kochle and Schneebeli (2014) & Kochle and Schneebeli (2014) & 677 & 4.6 \\
Kim and Jamieson Table 2 & Kochle and Schneebeli (2014) & Kochle and Schneebeli (2014) & 581 & 3.9 \\
Kim and Jamieson Table 2 & Bergfeld et al. (2023) & Kochle and Schneebeli (2014) & 465 & 3.1 \\
Geldsetzer and Jamieson (2000) & Bergfeld et al. (2023) & Kochle and Schneebeli (2014) & 443 & 3.0 \\
\bottomrule
\end{tabular}